# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170624_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='wind_speed',
            field=models.CharField(max_length=20),
        ),
    ]
